#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(COLLAPSEPAGECOMPONENT_LIB)
#  define COLLAPSEPAGECOMPONENT_EXPORT Q_DECL_EXPORT
# else
#  define COLLAPSEPAGECOMPONENT_EXPORT Q_DECL_IMPORT
# endif
#else
# define COLLAPSEPAGECOMPONENT_EXPORT
#endif
